val:
  - C:/Users/DOCTOR/Documents/GitHub/YOLOv8/ultralytics/datasets/bridge_small/DIOR_bridge_rgb30/images/val
  - C:/Users/DOCTOR/Documents/GitHub/YOLOv8/ultralytics/datasets/bridge_small/MASR_bridge_sar30/images/val
  - C:/Users/DOCTOR/Documents/GitHub/YOLOv8/ultralytics/datasets/bridge_small/MassMIND_bridge_infr30/images/val

nc: 4

names:
  0: ship
  1: harbor
  2: tank
  3: bridge
