train:
  - C:/Users/DOCTOR/Documents/GitHub/YOLOv8/ultralytics/datasets/total_bridge/images/train_rgb
  - C:/Users/DOCTOR/Documents/GitHub/YOLOv8/ultralytics/datasets/total_bridge/images/train_sar
  - C:/Users/DOCTOR/Documents/GitHub/YOLOv8/ultralytics/datasets/total_bridge/images/train_ir

val:
  - C:/Users/DOCTOR/Documents/GitHub/YOLOv8/ultralytics/datasets/total_bridge/images/train_rgb
  - C:/Users/DOCTOR/Documents/GitHub/YOLOv8/ultralytics/datasets/total_bridge/images/train_sar
  - C:/Users/DOCTOR/Documents/GitHub/YOLOv8/ultralytics/datasets/total_bridge/images/train_ir

nc: 1
names:
  0: bridge
