path: ultralytics/datasets/total_bridge_trainval

train:
  - images/train_rgb
  - images/train_sar
  - images/train_ir

val:
  - images/val_rgb
  - images/val_sar
  - images/val_ir

nc: 1

names:
  0: bridge
